# Generated by Django 4.1.2 on 2022-12-06 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lastname_1', models.CharField(max_length=60, null=True)),
                ('lastname_2', models.CharField(max_length=60, null=True)),
                ('grade', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('photo', models.ImageField(null=True, upload_to=users.utils.users_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
