# Generated by Django 4.1.2 on 2023-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_template_resume_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='content',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_level',
            field=models.CharField(choices=[('info', 'INFO'), ('contact', 'CONTACT'), ('work experience', 'WORK EXPERIENCE'), ('education', 'EDUCATION')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='template_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
