# Generated by Django 4.1.2 on 2023-01-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_template_content_resume_resume_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_level',
        ),
    ]
