# Generated by Django 4.1.2 on 2023-01-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_resume_resume_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecontact',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'PHONE'), ('email', 'EMAIL'), ('linkedin', 'LINKEDIN'), ('facebook', 'FACEBOOK'), ('instagram', 'INSTAGRAM'), ('whatsapp', 'WHATSAPP')], default='phone', max_length=40),
        ),
    ]
