# Generated by Django 4.1.2 on 2023-01-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_resumeeducation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
