# Generated by Django 4.1.2 on 2023-01-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_resumeeducation_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeCoursesCertifications',
            new_name='ResumeCourseCertification',
        ),
    ]
