# Generated by Django 4.1.2 on 2023-01-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_resumeeducation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecoursecertification',
            name='from_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
