# Generated by Django 4.1.2 on 2023-01-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_resumecoursecertification_from_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecontact',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resumelanguage',
            name='level',
            field=models.CharField(choices=[('basic', 'BASIC'), ('intermediate', 'INTERMEDIATE'), ('advanced', 'ADVANCED'), ('native', 'NATIVE')], default=None, max_length=40),
        ),
    ]
