# Generated by Django 4.2.2 on 2023-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_resumecontact_url_alter_resumelanguage_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecontact',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'PHONE'), ('email', 'EMAIL'), ('linkedin', 'LINKEDIN'), ('github', 'GITHUB'), ('stackoverflow', 'STACKOVERFLOW'), ('facebook', 'FACEBOOK'), ('instagram', 'INSTAGRAM'), ('whatsapp', 'WHATSAPP'), ('tiktok', 'TIKTOK')], default='phone', max_length=40),
        ),
    ]
