# Generated by Django 4.2.2 on 2023-06-26 17:29

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_resumecontact_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to=main.utils.resume_template_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='template',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
