# Generated by Django 4.2.2 on 2023-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_resume_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
