# Generated by Django 4.2.2 on 2023-06-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_resume_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeeducation',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeworkexperience',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
