# Generated by Django 4.2.2 on 2023-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_resumeeducation_current_resumeworkexperience_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resumeworkexperience',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
